version: '3.3'
services:
  il2-gb-dedicated-server:
    container_name: il2-gb-dedicated-server
    hostname: il2-gb-dedicated-server
    cap_add:
      - NET_RAW
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - PASSWORD=$VNCPASSWORD
      - IL2GBAUTOINSTALL=${IL2GBAUTOINSTALL:-0}
      - FORCEREINSTALL=${FORCEREINSTALL:-0}
      - AUTOSTART=${AUTOSTART:-0}
      - AUTOSTARTSDS=$AUTOSTARTSDS
      - SRSAUTOSTART=${SRSAUTOSTART:-0}
      - TIMEOUT=${TIMEOUT:-30}
    ports:
      # Webtop WebGUI ports    
      - '3000:3000/tcp' # Webtop HTTP port - TCP only.
      - '3001:3001/tcp' # Webtop HTTPs port - TCP only.

      # IL2 GB server Ports      
      - '28000:28000/tcp' # Multiplayer game traffic - TCP.
      - '28000:28000/udp' # Multiplayer game traffic - UDP.      
      - '28100:28100/tcp' # Multiplayer asset download traffic - TCP only.
      - '8991:8991/tcp' # Uncomment to enable remote console (don't forget to manually edit IP in SDS) - TCP only.

      # IL2 SimpleRadio Standalone (IL2-SRS) ports
      - '6002:6002/tcp' # Uncomment to enable IL2 SimpleRadio Standalone (IL2-SRS) - TCP and UDP.
      - '6002:6002/udp' # Uncomment to enable IL2 SimpleRadio Standalone (IL2-SRS) - TCP and UDP.      
    volumes:
      - '${HOME}/il2-gb-dedicated-server:/config/'
    # Setting seccomp to unconfined with security_opt is necessary if you encounter 'Failed to execute child process "bash": Failed to fdwalk: Operation not permitted' errors.
    # You should not unconfine unless necessary.
    # See also: https://docs.linuxserver.io/images/docker-webtop/#application-setup
    #security_opt:
      #- seccomp=unconfined
    networks:
      manage-0-net:
        ipv4_address: 172.16.200.20
      #il2-0-net:
        #ipv4_address: 192.168.0.232
    restart: always
    image: serverror/il2-gb-dedicated-server

networks:
  manage-0-net:
    ipam:
      driver: default
      config:
        - subnet: "172.16.200.0/24"
#  il2-0-net: # The bridge driver doesn't play well with IL2's DServer if connecting within the same LAN
#    driver: macvlan
#    driver_opts:
#      parent: eth0
#    ipam:
#      driver: default
#      config:
#        - subnet: 192.168.0.0/24
#          gateway: 192.168.0.1
