#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# Define a logging function to prefix output to the docker logs.
output_to_log() {
    sed  's/^/[s6-init-il2-gb-auto-installer-updater-oneshot] /'
}

# Set up error handling
handle_error() {
    local exit_code="$?"
    echo -e "Error occurred (Exit code: $exit_code)"  | output_to_log
    exit "$exit_code"
}
trap handle_error ERR

# Function for autoinstall
autoinstall() {
    sudo -u abc /app/il2_gb_server/wine-dedicated-il2-gb-automated-installer/il2-gb-dedicated-server-automatic-installer.sh | output_to_log
    exit 0
}

# Function for autoupdate
autoupdate() {
    # Believe it or not you can just call the same install command and it will update/validate/install.
    autoinstall
}

install_folder_path="/config/.wine/drive_c/Program Files/IL-2 Sturmovik Great Battles"

# Get/set default value for IL2GBAUTOINSTALL if not already set
IL2GBAUTOINSTALL="${IL2GBAUTOINSTALL:-0}"
echo -e "IL2GBAUTOINSTALL=$IL2GBAUTOINSTALL" | output_to_log

# Get/set default value for FORCEREINSTALL if not already set
FORCEREINSTALL="${FORCEREINSTALL:-0}"
echo -e "FORCEREINSTALL=$FORCEREINSTALL" | output_to_log

# Check if IL2GBAUTOINSTALL is set to 1 and do so.
if [ "$IL2GBAUTOINSTALL" -eq 1 ]; then
    echo -e "IL2GB auto install requested." | output_to_log
    if [ "$FORCEREINSTALL" -eq 1 ]; then
        # A force reinstall request
        echo -e "Force reinstall requested." | output_to_log
        # If a previous install is present get rid of it.
        if [ -d "$install_folder_path" ]; then
            echo "Removing detected previous installation." | output_to_log
            rm -rf "$install_folder_path"
            find /config/Desktop/ -name '*.desktop' ! -name 'Run_IL2_GB_Install.desktop' -delete
            autoinstall
        else
            echo "No previous installation detected." | output_to_log
            autoinstall
        fi
        exit 0
    fi
    # Not a force reinstall request so just install.
    autoinstall
    exit 0
fi

# If we get here then we must be updating
if [ "$IL2GBAUTOINSTALL" -eq 1 ]; then
    autoupdate
    exit 0
fi

# We shouldn't really get here
echo "Nothing further to do, exiting." | output_to_log
exit 0


